#! /bin/sh



pgrep -x sxhkd > /dev/null || sxhkd &

#bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d I II III  IV V VI

bspc config border_width 1
bspc config focused_border_color \#9147FF
#003333 = Color transparente
#03EBE1
bspc config normal_border_color \#003333
#003333
bspc config window_gap         3 # 12 original

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config normal_border_color  "$color1"
bspc config focused_border_color "$color15"
#bspc config urgent_border_color  "$color3"
#bspc config presel_border_color  "$color1"
bspc config presel_feedback_color "$color1"
bspc config active_border_color  "$color2"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Todos los apartados que no tienen un comentario al lado es porque su valor por defecto era 0
bspc config top_padding  0
bspc config left_padding 10
bspc config right_padding 10
bspc config bottom_padding 3 # original 45


#XSECURELOCK_DIM_COLOR="#1a1b26" \
#	XSECURELOCK_PASSWORD_PROMPT=emoticon \
#	XSECURELOCK_SHOW_HOSTNAME=0 \
#	XSECURELOCK_SHOW_USERNAME=0 \
#	XSECURELOCK_FONT="Hack Nerd Font Mono" \
#	xss-lock -n /usr/lib/xsecurelock/saver_xscreensaver -l -- xsecurelock

# Autostart
$HOME/.screenlayout/screen.sh &
picom &
compton --restore &
nitrogen --restore &

bash  ~/.config/polybar/candy/launch.sh &
wmname compiz &
mpd   &
ncmpcpp &
xsetroot -cursor_name left_ptr &
#$HOME/.config/polybar/launch.sh &

